name: pocketbase_auth_api
description: The interface provided by the pocketbase SDK to authenticate a valid user of the application.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auth_api:
    path: ../auth_api

  pocketbase: ^0.5.0+1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
